services:
  mysql_dev:
    image: mysql:8.0 
    container_name: wsp_mysql_dev
    restart: unless-stopped
    env_file:
      - .env
      - .env.development
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d #Solo si el volumne no existe, para inicializar la DB

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME:-nestjs}", "-p${DB_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data_dev: