FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Se genera en node_modules
RUN npm run prisma:generate 

RUN npm run build
RUN npm prune --omit=dev

FROM node:20-slim AS runtime
RUN apt-get update && apt-get install -y curl --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

# RUN npm run install:ci
# RUN npm install dotenv-cli --save

COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
# COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /app/node_modules ./node_modules

COPY prisma ./prisma
COPY prisma.config.ts ./

COPY entrypoint.sh ./
ENTRYPOINT ["sh", "entrypoint.sh"]